INSERT INTO role
VALUES(1, "ROLE_USER");
INSERT INTO role
VALUES(2, "ROLE_ADMIN");
INSERT INTO role
VALUES(3, "ROLE_RESTWORKER");
INSERT INTO role
VALUES(4, "ROLE_RESTADMIN");

INSERT INTO user_roles
VALUES(1, 2);
INSERT INTO user_roles
VALUES(1, 3);
INSERT INTO user_roles
VALUES(1, 4);
